name: Peter J. Kohler, PhD
title: pjkohler
markdown: kramdown
permalink: /news/:year/:month/:day/:title
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

include: ["_pages"]

plugins:
  - jekyll-sitemap

navigation:
- title: About Me
  url: /
- title: News
  url: /news/
- title: Research
  url: /research/
- title: Datasets
  url: /data/
- title: Publications
  url: /pubs/
- title: CV
  url: /cv/