name: Kohler Visual Neuroscience Laboratory
title: Kohler Visual Neuroscience Laboratory
markdown: kramdown
permalink: /:year/:month/:day/:title
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

include: ["_pages"]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
- title: About
  url: /
- title: Lab Members
  url: /lab-members/
- title: Research
  url: /research/
- title: Collaborators
  url: /collaborators/
- title: Online Experiments
  url: /online-exp/
- title: Datasets
  url: /data/
- title: Publications
  url: /pubs/
- title: CV
  url: /cv/

