name: Peter J. Kohler, PhD
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

navigation:
- title: About Me
  url: /
- title: News
  url: /blog/
- title: Research
  url: /research/
- title: Datasets
  url: /data/
- title: Publications
  url: /pubs/
- title: CV
  url: /cv/