name: Kohler Visual Neuroscience Laboratory
title: Kohler Visual Neuroscience Laboratory
url: https://www.kohlerlab.com # the base hostname & protocol for your site
image:
  path: /assets/logos/lab_logo_social.png
  height: 160
  width: 214
logo: /assets/logos/lab_logo_social.png
twitter:
  username: k_v_n_l
social:
  type: Organization
description: Dedicated to understanding how the brain gives rise to visual experience. Lead by Dr. Peter J. Kohler at York University.
markdown: kramdown
permalink: /:year/:month/:day/:title
github: [metadata]

defaults:
  - 
    scope:
      path: ""
    values:
      image: /assets/logos/lab_logo_social.png
      lang: en_CA
  -  
    scope:
      path: /assets/jspsych/
    values:
      sitemap: false
  -  
    scope:
      path: "/assets/*/*.pdf"
    values:
      sitemap: false

kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

include: ["_pages"]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
- title: About
  url: /
- title: Lab Members
  url: /lab-members/
- title: Research
  url: /research/
- title: Collaborators
  url: /collaborators/
- title: Online Experiments
  url: /online-exp/
- title: Datasets
  url: /data/
- title: Publications
  url: /pubs/

