name: Kohler Visual Neuroscience Laboratory
title: KVNL
markdown: kramdown
permalink: /:year/:month/:day/:title
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

include: ["_pages"]

plugins:
  - jekyll-sitemap

navigation:
- title: About
  url: /
- title: People
  url: /people/
- title: Research
  url: /research/
- title: Datasets
  url: /data/
- title: Publications
  url: /pubs/
- title: CV
  url: /cv/